- name: nodejs | Add the nodejs repository
  apt_repository:
    repo: ppa:chris-lea/node.js
    state: present

- name: node.js | Install the node.js package
  apt:
    pkg: nodejs
    state: present
