- name: Install nginx
  apt:
    pkg: nginx
    state: present

- name: Erase default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: set nginx location (subconf)
  template: src=subconf dest=/etc/nginx/conf.d/association-magic-board.subconf

- name: rdirect http to https
  template: src=conf dest=/etc/nginx/conf.d/secure.conf

- name: restart nginx
  command: 'service nginx restart'
